### PR TITLE
fix for title

### PR DESCRIPTION
**Pull request by sendilkumarn**
#51

### CODE REVIEW

**Comment by sendilkumarn** [comment]
Ping @gavinbarron

**Comment by gavinbarron** [comment]
Hey @sendilkumarn all of your PRs need merging with master there was another PR merged that you need to include in your branches

**Comment by sendilkumarn** [comment]
@gavinbarron I think this also good to go except for PR #68 others are good to go.

#68  -->  I think the same fix you also moved in. So we can neglect that.

**Comment by gavinbarron** [comment]
Still showing conflicts here

**Pull request closed without merging**
