### PR TITLE
Add namespaces to services to avoid name clashing with user applications.

### PR DESCRIPTION
**Pull request by atnstefan**
NOTE: CalendarData was renamed to just MaterialCalendarData because it is a public facing service, thus a shorter name is better.

### CODE REVIEW

**Comment by bradberger** [comment]
@atnstefan Thanks for taking the time to do this, always appreciate people who are willing to jump in and write code!

I'm just a little bit concerned that it's a breaking change and will require a version bump. Right now we're still just picking up users and I'm not sure about disrupting things that way right now. Is there another project that the naming conflicts with, or is it more of a one-time issue?

@gavinbarron Do you have any feedback?

**Comment by atnstefan** [comment]
@bradberger, Calendar and CalendarData are very common names for services or resources. I would be more than glad to rename them if you have better suggestion. For the PR I followed the Angular convention for the 'private' components and MaterialCalendarData for the 'public' service.

I first ran into this issue while I was trying out your code on a simple Angular app. I did not pay attention to the details of library and defined a Calendar resource. And of course the calendar was not working at all.

I did not bump the version on the PR because that is a release decision, but I agree that it should be at least bumped to the next minor.

**Comment by bradberger** [comment]
Thanks for the explanation. As I'm still a bit new to this whole public Angular directive thing, I'm learning as I go so that's appreciated.

**Comment by atnstefan** [comment]
@bradberger, any news about this PR? Any changes still needed before getting merged?

**Comment by bradberger** [comment]
@atnstefan Actually I just haven't gotten around to looking at it yet, we just had a new baby and things are a bit crazy, so I'm working on it. Nothing that I know of for you to do, I just need to sit down and look at it!

**Pull request merged**
