### PR TITLE
Disable Selection

### PR DESCRIPTION
**Pull request by sendilkumarn**
#59  

Disabled look is purposefully left out. Let me know if you want this to be added.

### CODE REVIEW

**Comment by gavinbarron** [comment]
Thanks for implementing this, it's missing the check inside the link function of the directive for $scope.isDisabled at about line 251 though.

**Comment by sendilkumarn** [comment]
@gavinbarron  I Said right, purposefully left that. It shows entire calendar in disabled look. It will be odd. If needed I will add.

**Comment by gavinbarron** [comment]
My personal opinion is that if a UI element is disabled and does nothing when you click on it it's better to give the user some visual clues that is the case so that they're not left wondering why their clicks do nothing.

**Comment by gavinbarron** [comment]
You'll need to update this with the changes that have been merged to master

**Comment by sendilkumarn** [comment]
Ping @gavinbarron

**Pull request merged**
